route:
    receiver: 'telegram'

receivers:
    - name: 'telegram'
      telegram_configs:
        - bot_token: token
          api_url: https://api.telegram.org
          chat_id: -12345678
          parse_mode: ''